import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import type { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen`}
      >
        <nav className="w-full bg-white shadow-sm py-4 px-8 flex gap-6 items-center">
          <Link href="/" className="font-bold text-xl text-blue-700">Gridfinity App</Link>
          <Link href="/canvas" className="text-gray-700 hover:text-blue-600 transition">Canvas</Link>
          <Link href="/checkout" className="text-gray-700 hover:text-blue-600 transition">Checkout</Link>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
